import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/sonner"
import Silk from "@/components/Silk";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-100`}>
        <div className="absolute inset-0 -z-10">
            <Silk speed={5} scale={1} color="#7B7481" noiseIntensity={1.5} rotation={0} />
          </div>
        <AuthProvider>
          <NavBar/>
            {children}
            
            <Toaster/>
        </AuthProvider>
      </body>
    </html>
  );
}
